### ISSUE TITLE
npm cannot resolve module

### ISSUE THREAD

**Issue by pongoman** [eljefedelrodeodeljefe/vue-prosemirror-2#1]
Hi,

Installing through npm results in these errors:

![](http://image.prntscr.com/image/ec11ec0177134569af6a613b09e56d82.png)
I installed the devDependacies myself and got it to work. Not sure if I made a mistake, just letting you know.

Thanks

**Comment by eljefedelrodeodeljefe** [comment]
Nah, it was my bad and I fixed it by having prosemirror as dependency. 6b3bf5bc9f0d3f43b15148a668a16144063a7265. Sorry for that and thanks for using this.
